// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cHRf3ZizA2R78gMzxJdxhVfU1dR4g7I',
    appId: '1:574021065794:web:ec74a546ebaf1d1c3a21db',
    messagingSenderId: '574021065794',
    projectId: 'ignite-smarani',
    authDomain: 'ignite-smarani.firebaseapp.com',
    storageBucket: 'ignite-smarani.appspot.com',
    measurementId: 'G-RP7GDZJKM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtabA9y8PiWx-7azO_tScYbtys4VIYFEU',
    appId: '1:574021065794:android:db06b43dbeb527d43a21db',
    messagingSenderId: '574021065794',
    projectId: 'ignite-smarani',
    storageBucket: 'ignite-smarani.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotPx4E9lzdt6oMcQ6HRDFGirS3T93ylY',
    appId: '1:574021065794:ios:388bb51b26237b213a21db',
    messagingSenderId: '574021065794',
    projectId: 'ignite-smarani',
    storageBucket: 'ignite-smarani.appspot.com',
    iosClientId: '574021065794-qlcu9sddvavkv97d1fuq2thl11esr128.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBotPx4E9lzdt6oMcQ6HRDFGirS3T93ylY',
    appId: '1:574021065794:ios:388bb51b26237b213a21db',
    messagingSenderId: '574021065794',
    projectId: 'ignite-smarani',
    storageBucket: 'ignite-smarani.appspot.com',
    iosClientId: '574021065794-qlcu9sddvavkv97d1fuq2thl11esr128.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
